name: Publish crate

on: workflow_dispatch

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    needs: ["build-binary", "publish-docker"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
